# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
]
