# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mendaftar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=30)),
                ('venue', models.TextField()),
                ('about', models.TextField(blank=True)),
                ('finished', models.BooleanField()),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_begin'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ktp', models.CharField(max_length=18)),
                ('nik', models.CharField(max_length=18)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_join', models.DateTimeField(auto_now=True)),
                ('target_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mendaftar.Event')),
            ],
            options={
                'ordering': ['date_join'],
            },
        ),
    ]
